
# Jekyll configuration for GitHub Pages
title: My Professional Resume
description: Professional resume and portfolio website
theme: jekyll-theme-minimal
baseurl: "/resume-muse-portal"
url: "https://alqushaibi.github.io"

# Exclude node dependencies and build files from Jekyll processing
exclude:
  - package.json
  - package-lock.json
  - node_modules/
  - vite.config.ts
  - tsconfig.json
  - tsconfig.node.json
  - "*.config.ts"
  - "*.config.js"
  - "/src/*.tsx"
  - "/src/*.ts"

# Jekyll SEO configuration
author: Your Name
social:
  name: Your Name
  links:
    - https://github.com/yourusername
    - https://linkedin.com/in/yourlinkedin

# Build settings
markdown: kramdown
permalink: pretty
